### ISSUE TITLE
Use composer to install drush

### ISSUE THREAD

**Issue by q0rban** [Lullabot/tugboat-registry#22]
It'd be nice on our webheads to install drush with `composer global require drush/drush`. That way if you want to switch versions, it's a known format.

**Comment by bchavet** [comment]
I'm kind of leaning toward deprecating the "drupal" images, and just making sure composer is installed on all of the PHP images. Then, users are free to install whatever version of drush they need. From what I understand, drush9 wants to be installed locally to a site anyway.

Thoughts?

**Comment by juampynr** [comment]
I have seen this approach growing and growing: https://github.com/drush-ops/drush-launcher.

**Comment by q0rban** [comment]
Related, we just switched the documentation for Drupal 8 to installing drush-launcher and using the drush from composer.json in the project. In which case, I think this is no longer an issue here?

**Comment by q0rban** [comment]
Actually, it is still an issue, as I think we need to remove drush altogether from the images in here, or replace with drush-launcher.
