### ISSUE TITLE
Support (or document) starting from official Docker images

### ISSUE THREAD

**Issue by q0rban** [Lullabot/tugboat-registry#24]
Due to the nature of the underlying filesystem and networking, Tugboat doesn't support official Docker images. `VOLUME` doesn't work, since by mounting a volume, we lose the availability to clone the data in the volume for Base Previews, and also would blow up disk usage for our cluster. Docker doesn't yet support a method to reset the `VOLUME` command (see moby/moby#3465). 

It's not ideal that Tugboat can't use the official images:

1. We need to maintain our own images—can't rely on community support
2. We may miss critical security updates
3. Deconstructing existing Dockerfiles into Tugboat-compatible ones can be tedious, and when things don't work, difficult to debug.
4. For projects that are already using Docker (for local development or even production hosting), we can't use existing images, resulting in "[it works on my machine](https://i.imgflip.com/9mqg4.jpg)!" syndrome.

Let's use this issue to:

1. Begin documenting how to best write images for Tugboat as it exists today (things to do / avoid)
2. Discuss the technical hurdles, and brainstorm a world where Tugboat could work with official images in some capacity
3. Note any discovered workarounds

**Comment by q0rban** [comment]
Here is one idea for a workaround: https://github.com/moby/moby/issues/3465#issuecomment-313389014

It'd be interesting to see what would happen with some of them that start from CentOS or other Linux flavors.

**Comment by mrdavidburns** [comment]
This actually came up while I was just demo'ing Tugboat to a client.
We use Docker for our local and we have been maintaining our own images. When they saw Tugboat was using `apache-php7-drupal` and `mysql` they asked if those were the public images, and if so then we can just use those for our local docker builds. This would make our locals as close to Tugboat if any odd errors were to pop up.

Sounds like using public docker images would be a nice feature to have.

**Comment by q0rban** [comment]
This could be a possibility: 

https://github.com/gdraheim/docker-copyedit

We could use it to programmatically remove the `VOLUME` declarations from a Docker hosted image.

Does this text from the README sound familiar?

> The wish to REMOVE ALL VOLUMES came from the fact that I did want to download a tested image for local tests where the data part should be committed to the history as well in order to turn back both program and data to a defined state so that another test run will start off the exact same checkpoint.

**Comment by bchavet** [comment]
Resolved by:

* https://github.com/Lullabot/tugboat/pull/2416
* https://github.com/TugboatQA/images
* https://hub.docker.com/u/tugboatqa/
