### ISSUE TITLE
Add a distro-specific cleanup script of some kind for Tugboat to execute prior to commit

### ISSUE THREAD

**Issue by q0rban** [Lullabot/tugboat-registry#30]
We often recommend cleaning up the apt, dpkg, /tmp dirs prior to commit, as that reduces the disk size of the Tugboat service. Rather than having this be a step that our users have to remember to perform, it makes sense for Tugboat to handle this directly.

**Comment by bchavet** [comment]
Resolved by:

* https://github.com/Lullabot/tugboat/pull/2416
* https://github.com/TugboatQA/images
* https://hub.docker.com/u/tugboatqa/
